modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="trademine_item_random"
version="1.0.0"
displayName="TradeMine Item Random"
displayURL="https://modrinth.com/mod/trademine-item-random"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="break08"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.trademine_item_random]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration