modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="trademine_item_random"
version="1.0.0"
displayName="TradeMine Item Random"
displayURL="https://modrinth.com/mod/trademine-item-random"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="break08"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.trademine_item_random]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.250,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.trademine_item_random]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration