modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="trademine_item_random"
version="1.0.0"
displayName="TradeMine Item Random"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.trademine_item_random]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.145,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.trademine_item_random]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration